### ISSUE TITLE
Add custom commands before restarting

### ISSUE THREAD

**Issue by hrCapitalIstABQ** [stevei5mc/AutoRestart#2]
Add custom commands brfore restarting.
For example:
#Whether to execute the command before restarting?
RestartCmd: true
  - wtransfer main

**Comment by stevei5mc** [comment]
Download build

link https://github.com/stevei5mc/AutoRestart/actions/runs/10040236828

Add to config
```yml
#重启前执行的命令(&con为控制台执行 @p 代表玩家名)
runcommand: true
commands:
  - "say hello world&con"
  - "help"
  - "say hello @p&con"
```
